PIH/hivmigration

- etl/pom.xml
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/SqlMigrator.java
This makes developing a single step easier and faster.
> Support step, revert, and limit command-line arguments

- .gitignore
- etl/src/main/java/org/pih/hivmigration/etl/sql/EncounterMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/PatientMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/SqlMigrator.java
https://pihemr.atlassian.net/browse/UHM-4794
> UHM-4794 Migrate "Migrate Encounters" to SQL Migrator

- etl/src/main/java/org/pih/hivmigration/etl/sql/InfantMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/SqlMigrator.java
https://pihemr.atlassian.net/browse/UHM-4791
Will change PR to be against `master` once https://github.com/PIH/hivmigration/pull/10 is merged.
> UHM-4791 Migrate "Migrate Infants" to SQL Migrator

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/ProgramMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/SqlMigrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/StagingDataMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-4792
> UHM-4792 Migrate "Migrate Programs" to SQL Migrator

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/VisitMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-4796
From https://wiki.openmrs.org/display/docs/How+to+create+visits+for+preexisting+encounters
> UHM-4796 Migrate "Create Visits" to SQL Migrator

- etl/src/main/java/org/pih/hivmigration/etl/sql/ProgramMigrator.groovy
Suggested changes to program migration.
> Program migration suggestions

- etl/src/main/java/org/pih/hivmigration/etl/sql/EncounterMigrator.groovy
After this update the EncounterMigrator ran fine in my machine in 5:36. Thanks for reviewing it.
> UHM-4799, add accompagnateur encounter type

- etl/src/main/java/org/pih/hivmigration/etl/sql/MedpickupsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
Hi @mseaton , this is just the first step that brings over to OpenMRS the HIV_DISPENSING and HIV_DISPENSING_MEDS. I am sure some column names might need to change? But, I hope everything else is according to what we discussed yesterday. Thanks. (the full import ran on my machine in 2:30)
> UHM-4799, migrate HIV_DISPENSING_MEDS to OpenMRS

- etl/src/main/java/org/pih/hivmigration/etl/sql/MedpickupsMigrator.groovy
Here is step#2 that creates all dispensing obs except the medication construct. I will work on this next. Thanks @mseaton , @mogoodrich and @brandones !
> UHM-4799, step 2 migrate dispensing obs

- etl/src/main/java/org/pih/hivmigration/etl/sql/ProcedureSetup.groovy
From Mark's feedback on https://pihemr.atlassian.net/browse/UHM-4797
> Guarantee that obs get a location_id

- etl/src/main/java/org/pih/hivmigration/etl/sql/ProgramMigrator.groovy
Relates to https://pihemr.atlassian.net/browse/UHM-4815
> Fix typo in program migrator, about outcome and outcome_date

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/VitalsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-4800
> UHM-4800 Migrate "Migrate Vitals" to SQL Migrator

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamExtraMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/ReturnVisitDateMigrator.groovy
Hi @mseaton , here is the migration script for NEXT_EXAM_DATE. Thanks!
> UHM-4801, migrate next exam date

- etl/src/main/java/org/pih/hivmigration/etl/sql/InfantMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/PatientMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/UserMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-4865
> UHM-4865 Log data irregularities during HIV data migration

- etl/src/main/java/org/pih/hivmigration/etl/sql/ProgramMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
https://pihemr.atlassian.net/browse/UHM-4815
> Clean up program migrator

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
https://pihemr.atlassian.net/browse/UHM-4800
> Make sure visits get created for vitals

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamExtraMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/LabResultMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/MedpickupsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/ObsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/SqlMigrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/VitalsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-4894
> UHM-4894 Obs migrator should iterate so that it doesn't stall out

- etl/src/main/java/org/pih/hivmigration/etl/sql/MedpickupsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/ObsLoadingMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-4832
This only accounts for "20. Treatment / Phrophylactic measures" through "22. Treatment anti-TB"
Documented https://pihemr.atlassian.net/wiki/spaces/ZL/pages/1052770307/ZL+HIV+Meds+Migration+Plan
ObsLoading takes ~10 minutes
> UHM-4832 Migration of treatment obs from HIV EMR to OpenMRS

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamExtraMigrator.groovy
There was one "Next Appt Date" in the Exam Extra table that linked to an accompagnateur which could potentially clash with Next Dispensed Date on the dispensing form.
This encounter was from 2007, and it didn't seem worth spending two much time worrying about it, so, for now I changed the script to *only* migrate next exam dates associated with "intake" and "followup" encounters.  All other next exam dates (currently just the 1 mentioned above) get logged in the data warnings table.
> UHM-4801: Migrate "Migrate Exam Extra Info" to SQL Migrator

- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
Fixes https://bamboo.pih-emr.org/browse/HIVM-EMJ-91/log
> Make function concept_uuid_from_mapping deterministic. 

- etl/src/main/java/org/pih/hivmigration/etl/sql/VitalsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-4800
> Exclude test patients from vitals migration

- etl/src/main/java/org/pih/hivmigration/etl/sql/PatientMigrator.groovy
Per UHM-4881, just logging to the data_warnings table the duplicate IDs. Thanks @mogoodrich !
> UHM-4881, log duplicate IDs to the data_warning table

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
This is related to https://pihemr.atlassian.net/browse/UHM-4905 . It may or may not resolve it, since it hasn't been determined what's supposed to happen. This seems like a reasonable thing to do for now though.
> Map old TB treatments

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamExtraMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/VisitMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-4834
> UHM-4834: Data Quality: Review/clean up multiple encounters at different locations at the same day

- etl/src/main/java/org/pih/hivmigration/etl/sql/EncounterMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/PatientMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/ProviderMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-3237
> UHM-3237 A few encounters in HIV_ENCOUNTERS don't have encounter datetimes

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamExtraMigrator.groovy
This is for migrating transferred_out locations. Thanks!
> UHM-4907, migrate transferred_out locations

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamExtraMigrator.groovy
@mogoodrich , I have removed the transfer_p obs from this migration task. Thanks for reviewing this update.
> UHM-4907, do not migrate transfer_p obs yet

- etl/src/main/java/org/pih/hivmigration/etl/sql/EncounterMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-3237
> Default null encounter_date to date_created

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-4832
I didn't test this locally, so it's on me if it breaks everything.
> ARV Tx names should be PIH:1282, grouped under PIH:6116

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamLabResultsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
https://pihemr.atlassian.net/browse/UHM-4950
This begins the ExamLabResults migrator.
> UHM-4950 Migrate CD4 from HIV_EXAM_LAB_RESULTS

- etl/src/main/java/org/pih/hivmigration/etl/sql/DataWarningsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/EncounterMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamExtraMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/InfantMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/PatientMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/ProgramMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/VisitMigrator.groovy
Handles both these tickets:
https://pihemr.atlassian.net/browse/UHM-4932
https://pihemr.atlassian.net/browse/UHM-4967
I've run the whole migration soup-to-nuts with most of these changes.  I did make a few last-minute tweaks, will run again this afternoon/evening before merging.
> UHM-4932 & UHM-4967

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamLabResultsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
https://pihemr.atlassian.net/browse/UHM-4951
> UHM-4951 migrate PPD from HIV_EXAM_LAB_RESULTS

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamLabResultsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-4953
> UHM-4953 migrate RPR test from HIV_EXAM_LAB_RESULTS. Also, fix data warnings.

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamLabResultsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-4955
> UHM-4955 migrate sputum test from HIV_EXAM_LAB_RESULTS

- etl/src/main/java/org/pih/hivmigration/etl/sql/EncounterMigrator.groovy
Do we also need to update all the obs migration scripts to exclude test patients?
> UHM-4969, do not migrate encounters with test patients

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamExtraMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamLabResultsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/LabResultMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/MedpickupsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/ObsLoadingMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
I think these are so far all places that we needed to filter out test patient data.
> UHM-4975, do not migrate obs from test patients

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamLabResultsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
https://pihemr.atlassian.net/browse/UHM-4970
> UHM-4970 migrate hemoglobin from HIV_EXAM_LAB_RESULTS

- etl/src/main/java/org/pih/hivmigration/etl/sql/EncounterMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/InfantMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/PatientMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/ProgramMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/VisitMigrator.groovy
- migration.properties
> UHM-4922: Create data warnings ETL/DW table

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-4966
> Fix TB mappings

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamExtraMigrator.groovy
This is for migrating the TB screening questions. Thanks!
> UHM-4976, migrate tb screening questions

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamExtraMigrator.groovy
This is to add bloody cough, chest pain and difficulty breathing questions. Thanks!
> UHM-4976, additional TB screening questions

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamLabResultsMigrator.groovy
Thanks @brandones  and @mogoodrich for reviewing this PR.
> UHM-4972, migrate Erythrocyte sedimentation rate test

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamLabResultsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/ObsMigrator.groovy
Response to feedback on https://pihemr.atlassian.net/browse/UHM-4950
> ExamLabResults that have test_date should use that for the obs.obs_datetime

- etl/src/main/java/org/pih/hivmigration/etl/sql/PatientMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5002
> UHM-5002 Migrate Patient Nickname to Person Name "Middle Name"

- etl/src/main/java/org/pih/hivmigration/etl/sql/InfantMigrator.groovy
This PR address both UHM-4982(exclude test infants) and UHM-4981(infants with a patient record). Thanks!
> UHM-4982, exclude children of test patients

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5013
> UHM-5013 Update HIV regimen treatment (Rx) for Data Migration

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/PcrTestsMigrator.groovy
Hi @mogoodrich , here is the PR for migrating the PCR tests. Thanks!
> UHM-4998, migrate PCR tests

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
Trivial; merging. A concept  mapping changed (or I had it wrong).
> Fix TB Tx concept HREZ -> RHZE

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5026
> UHM-5026 Fix prophylaxis and TB migration to support HIV Status section

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/RegistrationMigrator.groovy
I have created Registration encounters for all patients and recorded birthplaces for patients who had one in the system.
> UHM-5017, create registration encounters and record birthplaces

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/SqlMigrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/StagingTablesMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/TableStager.groovy
Creates generic table stager to move tables from Oracle to MySQL
> UHM-5028 Migrate HIV_INTAKE_FORMS table to OpenMRS

- etl/src/main/java/org/pih/hivmigration/etl/sql/StagingTablesMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/TableStager.groovy
https://pihemr.atlassian.net/browse/UHM-5031
> UHM-5031 Migrate HIV_FOLLOWUP_FORMS into OpenMRS

- etl/src/main/java/org/pih/hivmigration/etl/sql/FormsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5029
> UHM-5029 Migrate "Recommendation" from HIV EMR Intake to OpenMRS Intake Form

- etl/src/main/java/org/pih/hivmigration/etl/sql/FormsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5035
> UHM-5035 Map Progress Section on HIV EMR Followup Form to Progress Section on PIH EMR Followup Form

- etl/src/main/java/org/pih/hivmigration/etl/sql/DiagnosisMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/LocationMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/StagingTablesMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5036
> UHM-5036 Migrate HIV_PATIENT_DIAGNOSIS table

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/PreviousExposureMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/StagingTablesMigrator.groovy
> UHM-5039 Migrate HIV_PREVIOUS_EXPOSURES table - part 1

- etl/src/main/java/org/pih/hivmigration/etl/sql/RegistrationMigrator.groovy
@mogoodrich , here is the migration of all fields from the socioeconomics table. Thanks!
> UHM-5042, migrate all socio_economics data

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/PcrTestsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/PreviousExposureMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/RegistrationMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/StagingTablesMigrator.groovy
Restores #106 . The missing `setAutoIncrement` caused [this failure](https://bamboo.pih-emr.org/browse/HIVM-EMJ-170) in Bamboo.
> Restore HIV_PREVIOUS_EXPOSURES migration; add missing setAutoIncrement

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5026
> Fix prophylaxis start date migration

- etl/src/main/java/org/pih/hivmigration/etl/sql/DiagnosisMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5036
> Add comments and other diagnoses to DiagnosisMigrator

- etl/src/main/java/org/pih/hivmigration/etl/sql/DiagnosisMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5036
> Add Diagnosis start_date; migrate Diagnosis negatives also

- etl/src/main/java/org/pih/hivmigration/etl/sql/VisitMigrator.groovy
Part of https://pihemr.atlassian.net/browse/UHM-5075
> Don't create visits for registration encounters

- etl/src/main/java/org/pih/hivmigration/etl/sql/InfantMigrator.groovy
part 2 of https://pihemr.atlassian.net/browse/UHM-5075
> Create registration encounter for each infant

- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5026
> Fixes for UHM-5026 Fix prophylaxis and TB migration to support HIV Status section

- etl/src/main/java/org/pih/hivmigration/etl/sql/DiagnosisMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/SqlMigrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/StagingTablesMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5036
Also marks "yes" for other diagnoses.
> Deduplicate patient diagnoses in migration

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5090
> UHM-5090 Migrate current_tx.tb_other observation

- etl/src/main/java/org/pih/hivmigration/etl/sql/SocioEconomicsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/StagingTablesMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5041
> UHM-5041 Migrate HIV_SOCIOECONOMICS_EXTRA Tobacco/Alcohol questions to HIV Intake

- etl/src/main/java/org/pih/hivmigration/etl/sql/AdherenceMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
https://pihemr.atlassian.net/browse/UHM-5086
> UHM-5086 HIV Followup: Migrate Adherence section

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamSystemStatusMigrator.groovy
@mogoodrich , I got this HEENT normal obs concatenated into the value_text.
> UHM-5044, concatenate HEENT normal obs to value_text

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5090
Resolves
> For the free-text values that can’t be mapped, adding a free text field on the new form is a bigger discussion, but I think as part of this ticket we should at least set the “anti-TB treatment” radio set to have “yes” checked… as this makes it clearer that the patient is at least on TB treatment
So that if both a coded and non-coded treatment are provided, the coded treatment is the one that sets the "anti-TB treatment" radio.
> Ensure that multiple obs for 'currently on tb treatment' are not created

- etl/src/main/java/org/pih/hivmigration/etl/sql/EncounterMigrator.groovy
See https://github.com/PIH/hivmigration/pull/135
> Default null encounter_date only after logging warning

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5103
> UHM-5103 Fix TB Treatment migration on Followup Form and Intake Form

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5104
> UHM-5104 Migrate reason TB treatment changed or stopped

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/NutritionMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5101
> UHM-5101 Migrate Nutrition section on HIV EMR Follow-Up Form

- etl/src/main/java/org/pih/hivmigration/etl/sql/AdverseEventMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5102
> UHM-5102 Migrate Follow-Up Side Effects section 

- etl/src/main/java/org/pih/hivmigration/etl/sql/DiagnosisMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamExtraMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/FormsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/PreviousExposureMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/RegistrationMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/SocioEconomicsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/TableStager.groovy
https://pihemr.atlassian.net/browse/UHM-5097
The error happened in the first place because I got mixed up between `patient_id` and `source_patient_id`. I've fixed the table stager so that it renames columns appropriately.
> UHM-5097 Migrate HIV_SOCIOECOMICS (part 2) and HIV_SOCOECONOMICS_EXTRA

- etl/src/main/java/org/pih/hivmigration/etl/sql/ContactsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/StagingTablesMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5096
> UHM-5096 Migrate HIV_CONTACTS table 

- etl/src/main/java/org/pih/hivmigration/etl/sql/SocioEconomicsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5097
> UHM-5097 Socioeconomics fixes: education and floor

- etl/src/main/java/org/pih/hivmigration/etl/sql/SocioEconomicsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5097
> Fix secondary education concept

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
https://pihemr.atlassian.net/browse/UHM-5096
> Add contacts migrator to list of migrators

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/SocioEconomicAssistanceMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/StagingTablesMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
Also refactors the HIV_ORDERED_OTHER table migration out of TreatmentObsMigrator.
> UHM-5108 Migrate Socioeconomic Assistance Section on Intake and Followup

- etl/src/main/java/org/pih/hivmigration/etl/sql/ContactsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5096
Trivial; merging
> Switch to using PIH:CHILD for child relationship

- etl/src/main/java/org/pih/hivmigration/etl/sql/ContactsMigrator.groovy
Fixes incorrect mapping used in https://github.com/PIH/hivmigration/pull/155
Trivial, merging.
> Fix child concept mapping

- etl/src/main/java/org/pih/hivmigration/etl/sql/PreviousExposureMigrator.groovy
> Add more coded values to PreviousExposureMigrator

- etl/src/main/java/org/pih/hivmigration/etl/sql/PreviousExposureMigrator.groovy
> Migrate previous_exposure treatment_other values

- etl/src/main/java/org/pih/hivmigration/etl/sql/SocioEconomicAssistanceMigrator.groovy
> Fix socioeconomic assistance migrator

- etl/src/main/java/org/pih/hivmigration/etl/sql/PreviousExposureMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
> Fix previous exposure migrator to handle dates and other values

- etl/src/main/java/org/pih/hivmigration/etl/sql/SocioEconomicAssistanceMigrator.groovy
> UHM-5108 pt 3: Fix text for other types of socioecon assistance

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
I think this is all we need to do to migrate those non-coded medications?
> UHM-5098, migrate other current medications

- etl/src/main/java/org/pih/hivmigration/etl/sql/SocioEconomicAssistanceMigrator.groovy
> UHM-5108 pt 4: No repitition of 'other' assistance types; translations

- etl/src/main/java/org/pih/hivmigration/etl/sql/SocioEconomicAssistanceMigrator.groovy
Also restores Nutritional Aid migration, which was lost somehow.
> UHM-5108 pt 5: Migrate socioecon assist rows when comment = null and form_version < 3

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamSymptomsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
I still need to add a few more rows in the hivmigration_symptoms_map to complete the mapping of the symtoms names, but just wanted to make sure the model of this migration looks right to you. Thanks!
> UHM-5066, migrate HIV_EXAM_SYMPTOMS

- etl/src/main/java/org/pih/hivmigration/etl/sql/PreviousExposureMigrator.groovy
Would recommend using "Hide whitespace changes" for this one.
With reference to the bug screenshots in Jira:
> Pt 4 of UHM-5039 Migrate HIV_PREVIOUS_EXPOSURES table

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5106
This required pretty significant refactoring, but I think the result is nice, and quite fast.
> UHM-5106 Fix migration of Ordered ARV

- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/SampleDataMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5186
My database has 42754 patients in hivmigration_patients. That means there should be 213770 entries. This generates 201840. I don't know how to account for the discrepancy but it's pretty close, and I figured I'd submit this for review.
It also takes a long time. 1.5 hours on my machine. Most of that time is spent filling in the "unknown" and "no" answers.
> UHM-5186 Add Key Population sample data 

- etl/src/main/java/org/pih/hivmigration/etl/sql/FormsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-3134
Migrates into https://github.com/PIH/openmrs-config-zl/pull/52
> Add provider from intake and followup forms

- etl/src/main/java/org/pih/hivmigration/etl/sql/FormsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/LabResultMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-3134
> UHM-3134 Migrate provider data

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5110
> UHM-5110 Migrate/Fix Migration of Intake Prophylaxis section (20)

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
This reverts the reversion of #174 .
The code has already been reviewed, so I'm just going to merge. I did some testing with the new index (#179 ) and it seems like this now completes quickly.
> Restore UHM-5106 Fix migration of Ordered ARV (#174)

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5139
> UHM-5139 Migrate non-coded TB treatments "current_tx.tb_other" (Part II)

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5106
> UHM-5106 Fix migration of Ordered ARV - handle case where both ARV #1 and #2 are codifiable

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamSymptomsMigrator.groovy
Hi @mogoodrich , here is the update to only migrate symptoms captured on v3 intake form. Thanks!
> UHM-5066, migrate only symptoms captured on intake v3 form

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
@mogoodrich , this addresses the issue you reported here:
https://pihemr.atlassian.net/browse/UHM-5107?focusedCommentId=113255
THanks!
> UHM-5107, migrate non coded change arvs reason

- etl/src/main/java/org/pih/hivmigration/etl/sql/SocioEconomicAssistanceMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/StagingTablesMigrator.groovy
> Migrate SocioEcon assist data for follow-up encounters

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5139
> Migrate Status -> TB Other values also when there is a coded TB value

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamSymptomsMigrator.groovy
Good finding @mogoodrich ! I have addressed the latest issue you discovered with these symptoms migration. Thanks!
> UHM-5066, import from oracle only v3 intake symptoms

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
THis is just for migrating two of the obs from UHM-5087. Thanks!
> UHM-5087, migrate arv_start_date and arv_treatment_reason

- etl/src/main/java/org/pih/hivmigration/etl/sql/PcrTestsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5267
> UHM-5267 Tweak to HIV_PCR_TESTS

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
Per latest updates on UHM-5087, here is the migration of those obs. Thanks!
> UHM-5087, migrate arvs_for_accident and arvs_for_ptme obs

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
> UHM-5310, put ART start date in an obs group

- etl/src/main/java/org/pih/hivmigration/etl/sql/PcrTestsMigrator.groovy
@mogoodrich , I have replaced the HIV_PCR_TRACKING_VIEW with the entire select statement behind the view, and I just added the pcr_test_id. Thanks!
> UHM-5268, migrate pcr_test_id field to hivmigration_pcr_tests

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
> UHM-5310 Fix migration of ARV start date on Intake and Followup

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5110
> UHM-5110 Migrate/Fix Migration of Intake Prophylaxis section (20) again

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5110
> Fix migration of stopped prophylaxes

- etl/src/main/java/org/pih/hivmigration/etl/sql/InfantMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/ObsMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/VisitMigrator.groovy
Fix for https://pihemr.atlassian.net/browse/UHM-5292
> Fix UHM-5292 Migrate other data points from HIV_INFANTS table into OVC Intake encounter

- etl/src/main/java/org/pih/hivmigration/etl/sql/ExamLabResultsMigrator.groovy
Good catch, @mogoodrich ! Thanks!
> UHM-5270, remove duplicate chest xRay constructs

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5110
> Migrate all prophylaxis data

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
> UHM-5310: Don't add Other as ART for patients with no ART

- etl/src/main/java/org/pih/hivmigration/etl/sql/Setup.groovy
https://pihemr.atlassian.net/browse/UHM-5292
> Create proper UUID v5 implementation

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
> UHM-5310: Fix query for ART and ART-other

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
> Use separate temp tables for ART status & ART plan (UHM-5310)

- etl/src/main/java/org/pih/hivmigration/etl/sql/EncounterMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5181
> UHM-5181 Log warning about duplicate encounters of the same type

- etl/src/main/java/org/pih/hivmigration/etl/sql/EncounterMigrator.groovy
- etl/src/main/java/org/pih/hivmigration/etl/sql/Migrator.java
- etl/src/main/java/org/pih/hivmigration/etl/sql/NoteMigrator.groovy
https://pihemr.atlassian.net/browse/UHM-5316
> UHM-5316 Migrate "Note" encounter type

- etl/src/main/java/org/pih/hivmigration/etl/sql/TreatmentObsMigrator.groovy
> Ensure that ARV start date gets created for plan section of intake form even when no other data present (UHM-5310)
